-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 23:04:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FMVStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FMVStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FMVStore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `FMVStore` ;

-- -----------------------------------------------------
-- Table `FMVStore`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Supplier` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `contact_information` VARCHAR(100) NULL DEFAULT NULL,
  `supplier_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`supplier_id`),
  UNIQUE INDEX `supplier_id_UNIQUE` (`supplier_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Store` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `store_address` VARCHAR(100) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`store_id`),
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `supply_date` DATETIME NOT NULL,
  `receive_date` DATETIME NOT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC) VISIBLE,
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `storeid_transaction_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `storeid_transaction`
    FOREIGN KEY (`store_id`)
    REFERENCES `FMVStore`.`Store` (`store_id`),
  CONSTRAINT `supplierid_transaction`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `FMVStore`.`Supplier` (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Batch` (
  `batch_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`batch_id`),
  UNIQUE INDEX `batch_id_UNIQUE` (`batch_id` ASC) VISIBLE,
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `transactionid_batch_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `supplierid_batch`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `FMVStore`.`Supplier` (`supplier_id`),
  CONSTRAINT `transactionid_batch`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `FMVStore`.`Transaction` (`transaction_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `plu_id` INT NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL,
  `image` VARCHAR(200) NULL DEFAULT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Batch_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Batch_Product` (
  `batch_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `manufacture_date` DATETIME NOT NULL,
  `expire_date` DATETIME NOT NULL,
  INDEX `batchid_batch_product_idx` (`batch_id` ASC) VISIBLE,
  INDEX `productid_batch_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `batchid_batch_product`
    FOREIGN KEY (`batch_id`)
    REFERENCES `FMVStore`.`Batch` (`batch_id`),
  CONSTRAINT `productid_batch_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `FMVStore`.`Product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `date_of_birth` DATETIME NULL DEFAULT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `sex` INT NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Discount` (
  `discount_code` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `description` VARCHAR(60) NULL DEFAULT NULL,
  `apply_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`discount_code`),
  UNIQUE INDEX `discount_code_UNIQUE` (`discount_code` ASC) VISIBLE,
  INDEX `productid_discount_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `productid_discount`
    FOREIGN KEY (`product_id`)
    REFERENCES `FMVStore`.`Product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `date_of_birth` DATETIME NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC) VISIBLE,
  INDEX `storeid_employee_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `storeid_employee`
    FOREIGN KEY (`store_id`)
    REFERENCES `FMVStore`.`Store` (`store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `order_date` DATETIME NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `customerid_order_idx` (`customer_id` ASC) VISIBLE,
  INDEX `employeeid_order_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `customerid_order`
    FOREIGN KEY (`customer_id`)
    REFERENCES `FMVStore`.`Customer` (`customer_id`),
  CONSTRAINT `employeeid_order`
    FOREIGN KEY (`employee_id`)
    REFERENCES `FMVStore`.`Employee` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Order_Detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Order_Detail` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `orderid_order_detail_idx` (`order_id` ASC) VISIBLE,
  INDEX `productid_order_detail_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `orderid_order_detail`
    FOREIGN KEY (`order_id`)
    REFERENCES `FMVStore`.`Order` (`order_id`),
  CONSTRAINT `productid_order_detail`
    FOREIGN KEY (`product_id`)
    REFERENCES `FMVStore`.`Product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Product_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Product_Category` (
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  INDEX `productid_product_category_idx` (`product_id` ASC) VISIBLE,
  INDEX `category_id_product_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `FMVStore`.`Category` (`category_id`),
  CONSTRAINT `productid_product_category`
    FOREIGN KEY (`product_id`)
    REFERENCES `FMVStore`.`Product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Shift` (
  `shift_id` INT NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  PRIMARY KEY (`shift_id`),
  UNIQUE INDEX `shift_id_UNIQUE` (`shift_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Storage` (
  `store_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  INDEX `storeid_storage_idx` (`store_id` ASC) VISIBLE,
  INDEX `productid_storage_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `productid_storage`
    FOREIGN KEY (`product_id`)
    REFERENCES `FMVStore`.`Product` (`product_id`),
  CONSTRAINT `storeid_storage`
    FOREIGN KEY (`store_id`)
    REFERENCES `FMVStore`.`Store` (`store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FMVStore`.`Timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FMVStore`.`Timetable` (
  `employee_id` INT NOT NULL,
  `shift_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  INDEX `employeeid_timetable_idx` (`employee_id` ASC) VISIBLE,
  INDEX `shiftid_timetable_idx` (`shift_id` ASC) VISIBLE,
  CONSTRAINT `employeeid_timetable`
    FOREIGN KEY (`employee_id`)
    REFERENCES `FMVStore`.`Employee` (`employee_id`),
  CONSTRAINT `shiftid_timetable`
    FOREIGN KEY (`shift_id`)
    REFERENCES `FMVStore`.`Shift` (`shift_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
