server:
  port: 8080
  servlet:
    context-path: /store
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/final"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect